services:
  web:
    image: nginx:latest
    privileged: true
    network_mode: host
    pid: host
    ipc: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

    environment:
      - APP_ENV=production